const HotelUser = require("../models/Hotel.user");

/**
 * Seed complete HotelUser data
 * Now with 12 hotels for testing:
 * - 6 in Delhi (including the original 1)
 * - 4 in Noida (including the original 1)
 * - 2 in Gurugram (Gurgaon)
 * - 2 in Jaipur
 */
const seedHotels = async () => {
  const hotels = [
    // ================= DELHI (6 total) =================
    {
      hotel_name: "Hotel Delhi Palace",
      hotel_zone: "North Delhi",
      hotel_address: "Karol Bagh, New Delhi",
      hotel_owner: "Ramesh Sharma",
      hotel_phone: "9999990001",
      amenities: {
        AC: true,
        freeWifi: true,
        kitchen: true,
        TV: true,
        powerBackup: true,
        geyser: true,
        parkingFacility: true,
        elevator: true,
        cctvCameras: true,
        diningArea: true,
        privateEntrance: false,
        reception: true,
        caretaker: true,
        security: true,
        checkIn24_7: true,
        dailyHousekeeping: true,
        fireExtinguisher: true,
        firstAidKit: true,
        buzzerDoorBell: false,
        attachedBathroom: true,
      },
      contactNumberVerify: true,
      isVerifiedTag: true,
      DocumentUploaded: true,
      DocumentUploadedVerified: true,
      isBlockByAdmin: false,
      ClearAllCheckOut: false,
      hotel_main_show_image:
        "https://images.unsplash.com/photo-1566073771259-6a8506099945?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
      area: "Karol Bagh",
      hotel_geo_location: {
        type: "Point",
        coordinates: [77.1900, 28.6517], // Karol Bagh approx
      },
      property_pdf: "https://example.com/property-doc.pdf",
      bh: "BH-DEL-001",
      isOnline: true,
      BhJsonData: {
        bhCode: "BH001",
        manager: "Amit Verma",
      },
      lastNotificationSent: new Date(),
      otp: 123456,
      otp_expires: new Date(Date.now() + 10 * 60 * 1000),
      isPaid: true,
      RechargeData: {
        rechargePlan: "MONTHLY",
        expireData: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
        approveRecharge: true,
        onHowManyEarning: "Unlimited",
        whichDateRecharge: new Date(),
      },
      Documents: [
        { d_type: "Aadhar", d_url: "https://example.com/aadhar.pdf", d_public_id: "aadhar_001" },
        { d_type: "PAN", d_url: "https://example.com/pan.pdf", d_public_id: "pan_001" },
      ],
    },
    {
      hotel_name: "Connaught Place Luxury Inn",
      hotel_zone: "Central Delhi",
      hotel_address: "Connaught Place, New Delhi",
      hotel_owner: "Priya Mehta",
      hotel_phone: "9999990002",
      amenities: { /* varied amenities */ AC: true, freeWifi: true, kitchen: false, TV: true, powerBackup: true, geyser: true, parkingFacility: false, elevator: true, cctvCameras: true, diningArea: true, privateEntrance: true, reception: true, caretaker: false, security: true, checkIn24_7: true, dailyHousekeeping: true, fireExtinguisher: true, firstAidKit: true, buzzerDoorBell: true, attachedBathroom: true },
      contactNumberVerify: true,
      isVerifiedTag: true,
      DocumentUploaded: true,
      DocumentUploadedVerified: true,
      isBlockByAdmin: false,
      ClearAllCheckOut: false,
      hotel_main_show_image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
      area: "Connaught Place",
      hotel_geo_location: { type: "Point", coordinates: [77.2167, 28.6304] }, // Connaught Place
      property_pdf: "https://example.com/cp-property.pdf",
      bh: "BH-DEL-002",
      isOnline: true,
      BhJsonData: { bhCode: "BH002", manager: "Rajesh Kumar" },
      lastNotificationSent: new Date(),
      otp: 987654,
      otp_expires: new Date(Date.now() + 15 * 60 * 1000),
      isPaid: true,
      RechargeData: { rechargePlan: "YEARLY", expireData: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000), approveRecharge: true, onHowManyEarning: "Unlimited", whichDateRecharge: new Date() },
      Documents: [{ d_type: "Aadhar", d_url: "https://example.com/aadhar2.pdf", d_public_id: "aadhar_002" }],
    },
    {
      hotel_name: "Paharganj Budget Stay",
      hotel_zone: "Central Delhi",
      hotel_address: "Main Bazaar, Paharganj, New Delhi",
      hotel_owner: "Anil Gupta",
      hotel_phone: "9999990003",
      amenities: { AC: true, freeWifi: true, kitchen: false, TV: true, powerBackup: false, geyser: true, parkingFacility: false, elevator: false, cctvCameras: true, diningArea: false, privateEntrance: false, reception: true, caretaker: true, security: false, checkIn24_7: true, dailyHousekeeping: false, fireExtinguisher: true, firstAidKit: true, buzzerDoorBell: false, attachedBathroom: true },
      contactNumberVerify: true,
      isVerifiedTag: false,
      DocumentUploaded: true,
      DocumentUploadedVerified: false,
      isBlockByAdmin: false,
      ClearAllCheckOut: false,
      hotel_main_show_image: "https://images.unsplash.com/photo-1522708323590-d173e9960b3f?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
      area: "Paharganj",
      hotel_geo_location: { type: "Point", coordinates: [77.2135, 28.6452] },
      property_pdf: "https://example.com/paharganj-property.pdf",
      bh: "BH-DEL-003",
      isOnline: false,
      BhJsonData: { bhCode: "BH003", manager: "Sanjay Singh" },
      lastNotificationSent: null,
      otp: 112233,
      otp_expires: new Date(Date.now() + 5 * 60 * 1000),
      isPaid: false,
      RechargeData: { rechargePlan: "TRIAL", expireData: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), approveRecharge: false, onHowManyEarning: "Limited", whichDateRecharge: new Date() },
      Documents: [],
    },
    {
      hotel_name: "Aerocity Grand Hotel",
      hotel_zone: "South West Delhi",
      hotel_address: "Indira Gandhi International Airport, New Delhi",
      hotel_owner: "Vikram Singh",
      hotel_phone: "9999990004",
      amenities: { AC: true, freeWifi: true, kitchen: false, TV: true, powerBackup: true, geyser: true, parkingFacility: true, elevator: true, cctvCameras: true, diningArea: true, privateEntrance: true, reception: true, caretaker: true, security: true, checkIn24_7: true, dailyHousekeeping: true, fireExtinguisher: true, firstAidKit: true, buzzerDoorBell: true, attachedBathroom: true },
      contactNumberVerify: true,
      isVerifiedTag: true,
      DocumentUploaded: true,
      DocumentUploadedVerified: true,
      isBlockByAdmin: false,
      ClearAllCheckOut: false,
      hotel_main_show_image: "https://images.unsplash.com/photo-1542314831-0682d6f8e3e5?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
      area: "Aerocity",
      hotel_geo_location: { type: "Point", coordinates: [77.1231, 28.5514] }, // Aerocity approx
      property_pdf: "https://example.com/aerocity-property.pdf",
      bh: "BH-DEL-004",
      isOnline: true,
      BhJsonData: { bhCode: "BH004", manager: "Meera Joshi" },
      lastNotificationSent: new Date(),
      otp: 445566,
      otp_expires: new Date(Date.now() + 10 * 60 * 1000),
      isPaid: true,
      RechargeData: { rechargePlan: "MONTHLY", expireData: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000), approveRecharge: true, onHowManyEarning: "Unlimited", whichDateRecharge: new Date() },
      Documents: [{ d_type: "PAN", d_url: "https://example.com/pan2.pdf", d_public_id: "pan_002" }],
    },
    {
      hotel_name: "South Extension Comfort Lodge",
      hotel_zone: "South Delhi",
      hotel_address: "South Extension Part II, New Delhi",
      hotel_owner: "Neha Kapoor",
      hotel_phone: "9999990010",
      amenities: { AC: true, freeWifi: true, kitchen: true, TV: true, powerBackup: true, geyser: true, parkingFacility: true, elevator: false, cctvCameras: true, diningArea: false, privateEntrance: false, reception: true, caretaker: true, security: true, checkIn24_7: false, dailyHousekeeping: true, fireExtinguisher: true, firstAidKit: true, buzzerDoorBell: true, attachedBathroom: true },
      contactNumberVerify: true,
      isVerifiedTag: false,
      DocumentUploaded: true,
      DocumentUploadedVerified: true,
      isBlockByAdmin: false,
      ClearAllCheckOut: false,
      hotel_main_show_image: "https://images.unsplash.com/photo-1582719478250-c89ccc43d245?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
      area: "South Extension",
      hotel_geo_location: { type: "Point", coordinates: [77.2200, 28.5672] },
      property_pdf: "https://example.com/south-ex-property.pdf",
      bh: "BH-DEL-005",
      isOnline: true,
      BhJsonData: { bhCode: "BH005", manager: "Arjun Patel" },
      lastNotificationSent: new Date(),
      otp: 778899,
      otp_expires: new Date(Date.now() + 10 * 60 * 1000),
      isPaid: false,
      RechargeData: { rechargePlan: "TRIAL", expireData: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000), approveRecharge: true, onHowManyEarning: "Limited", whichDateRecharge: new Date() },
      Documents: [],
    },
    {
      hotel_name: "Greater Kailash Premium Stay",
      hotel_zone: "South Delhi",
      hotel_address: "Greater Kailash I, New Delhi",
      hotel_owner: "Rohan Malhotra",
      hotel_phone: "9999990011",
      amenities: { AC: true, freeWifi: true, kitchen: false, TV: true, powerBackup: true, geyser: true, parkingFacility: true, elevator: true, cctvCameras: true, diningArea: true, privateEntrance: true, reception: true, caretaker: false, security: true, checkIn24_7: true, dailyHousekeeping: true, fireExtinguisher: true, firstAidKit: true, buzzerDoorBell: false, attachedBathroom: true },
      contactNumberVerify: true,
      isVerifiedTag: true,
      DocumentUploaded: true,
      DocumentUploadedVerified: true,
      isBlockByAdmin: false,
      ClearAllCheckOut: false,
      hotel_main_show_image: "https://images.unsplash.com/photo-1564501049412-61c2a308ebee?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
      area: "Greater Kailash",
      hotel_geo_location: { type: "Point", coordinates: [77.2425, 28.5494] },
      property_pdf: "https://example.com/gk-property.pdf",
      bh: "BH-DEL-006",
      isOnline: false,
      BhJsonData: { bhCode: "BH006", manager: "Kavita Rao" },
      lastNotificationSent: null,
      otp: 223344,
      otp_expires: new Date(Date.now() + 5 * 60 * 1000),
      isPaid: true,
      RechargeData: { rechargePlan: "MONTHLY", expireData: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000), approveRecharge: true, onHowManyEarning: "Unlimited", whichDateRecharge: new Date() },
      Documents: [{ d_type: "Aadhar", d_url: "https://example.com/aadhar3.pdf", d_public_id: "aadhar_003" }],
    },

    // ================= NOIDA (4 total) =================
    {
      hotel_name: "Noida Comfort Stay",
      hotel_zone: "Sector 18",
      hotel_address: "Sector 18, Noida",
      hotel_owner: "Suresh Yadav",
      hotel_phone: "9999990005",
      amenities: {
        AC: true,
        freeWifi: true,
        kitchen: false,
        TV: true,
        powerBackup: true,
        geyser: true,
        parkingFacility: true,
        elevator: true,
        cctvCameras: true,
        diningArea: false,
        privateEntrance: false,
        reception: true,
        caretaker: true,
        security: true,
        checkIn24_7: false,
        dailyHousekeeping: true,
        fireExtinguisher: true,
        firstAidKit: true,
        buzzerDoorBell: true,
        attachedBathroom: true,
      },
      contactNumberVerify: true,
      isVerifiedTag: false,
      DocumentUploaded: true,
      DocumentUploadedVerified: false,
      isBlockByAdmin: false,
      ClearAllCheckOut: false,
      hotel_main_show_image:
        "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
      area: "Sector 18",
      hotel_geo_location: {
        type: "Point",
        coordinates: [77.3234, 28.5712], // Sector 18 Noida approx
      },
      property_pdf: "https://example.com/noida-property.pdf",
      bh: "BH-NOI-001",
      isOnline: false,
      BhJsonData: {
        bhCode: "BH007",
        manager: "Neha Singh",
      },
      lastNotificationSent: null,
      otp: 654321,
      otp_expires: new Date(Date.now() + 5 * 60 * 1000),
      isPaid: false,
      RechargeData: {
        rechargePlan: "TRIAL",
        expireData: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
        approveRecharge: false,
        onHowManyEarning: "Limited",
        whichDateRecharge: new Date(),
      },
      Documents: [],
    },
    {
      hotel_name: "Sector 62 Tech Hub Hotel",
      hotel_zone: "Sector 62",
      hotel_address: "Sector 62, Noida",
      hotel_owner: "Deepak Agarwal",
      hotel_phone: "9999990006",
      amenities: { AC: true, freeWifi: true, kitchen: false, TV: true, powerBackup: true, geyser: true, parkingFacility: true, elevator: true, cctvCameras: true, diningArea: true, privateEntrance: false, reception: true, caretaker: true, security: true, checkIn24_7: true, dailyHousekeeping: true, fireExtinguisher: true, firstAidKit: true, buzzerDoorBell: true, attachedBathroom: true },
      contactNumberVerify: true,
      isVerifiedTag: true,
      DocumentUploaded: true,
      DocumentUploadedVerified: true,
      isBlockByAdmin: false,
      ClearAllCheckOut: false,
      hotel_main_show_image: "https://images.unsplash.com/photo-1578683015141-0b6dd2c1c2d3?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
      area: "Sector 62",
      hotel_geo_location: { type: "Point", coordinates: [77.3619, 28.6140] },
      property_pdf: "https://example.com/sector62-property.pdf",
      bh: "BH-NOI-002",
      isOnline: true,
      BhJsonData: { bhCode: "BH008", manager: "Rohit Sharma" },
      lastNotificationSent: new Date(),
      otp: 556677,
      otp_expires: new Date(Date.now() + 10 * 60 * 1000),
      isPaid: true,
      RechargeData: { rechargePlan: "MONTHLY", expireData: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000), approveRecharge: true, onHowManyEarning: "Unlimited", whichDateRecharge: new Date() },
      Documents: [{ d_type: "Aadhar", d_url: "https://example.com/aadhar4.pdf", d_public_id: "aadhar_004" }],
    },
    {
      hotel_name: "Greater Noida Express Stay",
      hotel_zone: "Greater Noida",
      hotel_address: "Alpha I, Greater Noida",
      hotel_owner: "Manish Jain",
      hotel_phone: "9999990012",
      amenities: { AC: true, freeWifi: true, kitchen: true, TV: true, powerBackup: true, geyser: true, parkingFacility: true, elevator: true, cctvCameras: false, diningArea: false, privateEntrance: true, reception: true, caretaker: true, security: true, checkIn24_7: false, dailyHousekeeping: true, fireExtinguisher: true, firstAidKit: true, buzzerDoorBell: false, attachedBathroom: true },
      contactNumberVerify: true,
      isVerifiedTag: false,
      DocumentUploaded: true,
      DocumentUploadedVerified: false,
      isBlockByAdmin: false,
      ClearAllCheckOut: false,
      hotel_main_show_image: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
      area: "Greater Noida",
      hotel_geo_location: { type: "Point", coordinates: [77.5039, 28.4744] },
      property_pdf: "https://example.com/gnoida-property.pdf",
      bh: "BH-NOI-003",
      isOnline: false,
      BhJsonData: { bhCode: "BH009", manager: "Pooja Verma" },
      lastNotificationSent: null,
      otp: 889900,
      otp_expires: new Date(Date.now() + 5 * 60 * 1000),
      isPaid: false,
      RechargeData: { rechargePlan: "TRIAL", expireData: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), approveRecharge: false, onHowManyEarning: "Limited", whichDateRecharge: new Date() },
      Documents: [],
    },
    {
      hotel_name: "Sector 137 Modern Lodge",
      hotel_zone: "Sector 137",
      hotel_address: "Sector 137, Noida Expressway",
      hotel_owner: "Ankit Saxena",
      hotel_phone: "9999990013",
      amenities: { AC: true, freeWifi: true, kitchen: false, TV: true, powerBackup: true, geyser: true, parkingFacility: true, elevator: true, cctvCameras: true, diningArea: true, privateEntrance: false, reception: true, caretaker: true, security: true, checkIn24_7: true, dailyHousekeeping: true, fireExtinguisher: true, firstAidKit: true, buzzerDoorBell: true, attachedBathroom: true },
      contactNumberVerify: true,
      isVerifiedTag: true,
      DocumentUploaded: true,
      DocumentUploadedVerified: true,
      isBlockByAdmin: false,
      ClearAllCheckOut: false,
      hotel_main_show_image: "https://images.unsplash.com/photo-1560200352-ce8f8b5c4c8c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
      area: "Sector 137",
      hotel_geo_location: { type: "Point", coordinates: [77.4075, 28.5020] },
      property_pdf: "https://example.com/sector137-property.pdf",
      bh: "BH-NOI-004",
      isOnline: true,
      BhJsonData: { bhCode: "BH010", manager: "Vivek Mishra" },
      lastNotificationSent: new Date(),
      otp: 334455,
      otp_expires: new Date(Date.now() + 10 * 60 * 1000),
      isPaid: true,
      RechargeData: { rechargePlan: "MONTHLY", expireData: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000), approveRecharge: true, onHowManyEarning: "Unlimited", whichDateRecharge: new Date() },
      Documents: [{ d_type: "PAN", d_url: "https://example.com/pan3.pdf", d_public_id: "pan_003" }],
    },

    // ================= GURUGRAM (GURGAON) (2) =================
    {
      hotel_name: "Cyber City Business Hotel",
      hotel_zone: "DLF Cyber City",
      hotel_address: "DLF Cyber City, Gurugram",
      hotel_owner: "Aditya Bhatia",
      hotel_phone: "9999990007",
      amenities: { AC: true, freeWifi: true, kitchen: false, TV: true, powerBackup: true, geyser: true, parkingFacility: true, elevator: true, cctvCameras: true, diningArea: true, privateEntrance: true, reception: true, caretaker: false, security: true, checkIn24_7: true, dailyHousekeeping: true, fireExtinguisher: true, firstAidKit: true, buzzerDoorBell: true, attachedBathroom: true },
      contactNumberVerify: true,
      isVerifiedTag: true,
      DocumentUploaded: true,
      DocumentUploadedVerified: true,
      isBlockByAdmin: false,
      ClearAllCheckOut: false,
      hotel_main_show_image: "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
      area: "Cyber City",
      hotel_geo_location: { type: "Point", coordinates: [77.0888, 28.4935] },
      property_pdf: "https://example.com/cybercity-property.pdf",
      bh: "BH-GUR-001",
      isOnline: true,
      BhJsonData: { bhCode: "BH011", manager: "Sonia Ahuja" },
      lastNotificationSent: new Date(),
      otp: 667788,
      otp_expires: new Date(Date.now() + 10 * 60 * 1000),
      isPaid: true,
      RechargeData: { rechargePlan: "YEARLY", expireData: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000), approveRecharge: true, onHowManyEarning: "Unlimited", whichDateRecharge: new Date() },
      Documents: [{ d_type: "Aadhar", d_url: "https://example.com/aadhar5.pdf", d_public_id: "aadhar_005" }],
    },
    {
      hotel_name: "Golf Course Road Residency",
      hotel_zone: "Golf Course Road",
      hotel_address: "Golf Course Road, Gurugram",
      hotel_owner: "Karan Oberoi",
      hotel_phone: "9999990008",
      amenities: { AC: true, freeWifi: true, kitchen: true, TV: true, powerBackup: true, geyser: true, parkingFacility: true, elevator: true, cctvCameras: true, diningArea: true, privateEntrance: false, reception: true, caretaker: true, security: true, checkIn24_7: false, dailyHousekeeping: true, fireExtinguisher: true, firstAidKit: true, buzzerDoorBell: false, attachedBathroom: true },
      contactNumberVerify: true,
      isVerifiedTag: false,
      DocumentUploaded: true,
      DocumentUploadedVerified: false,
      isBlockByAdmin: false,
      ClearAllCheckOut: false,
      hotel_main_show_image: "https://images.unsplash.com/photo-1631049307268-da2043436fd2?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
      area: "Golf Course Road",
      hotel_geo_location: { type: "Point", coordinates: [77.1016, 28.4563] },
      property_pdf: "https://example.com/golfcourse-property.pdf",
      bh: "BH-GUR-002",
      isOnline: false,
      BhJsonData: { bhCode: "BH012", manager: "Ritu Malhotra" },
      lastNotificationSent: null,
      otp: 990011,
      otp_expires: new Date(Date.now() + 5 * 60 * 1000),
      isPaid: false,
      RechargeData: { rechargePlan: "TRIAL", expireData: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), approveRecharge: false, onHowManyEarning: "Limited", whichDateRecharge: new Date() },
      Documents: [],
    },

    // ================= JAIPUR (2) =================
    {
      hotel_name: "Pink City Heritage Hotel",
      hotel_zone: "Old City",
      hotel_address: "Near Hawa Mahal, Jaipur",
      hotel_owner: "Mahendra Singh",
      hotel_phone: "9999990009",
      amenities: { AC: true, freeWifi: true, kitchen: false, TV: true, powerBackup: true, geyser: true, parkingFacility: false, elevator: false, cctvCameras: true, diningArea: true, privateEntrance: true, reception: true, caretaker: true, security: true, checkIn24_7: true, dailyHousekeeping: true, fireExtinguisher: true, firstAidKit: true, buzzerDoorBell: true, attachedBathroom: true },
      contactNumberVerify: true,
      isVerifiedTag: true,
      DocumentUploaded: true,
      DocumentUploadedVerified: true,
      isBlockByAdmin: false,
      ClearAllCheckOut: false,
      hotel_main_show_image: "https://images.unsplash.com/photo-1582719471384-89494b5b0b24?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
      area: "Hawa Mahal",
      hotel_geo_location: { type: "Point", coordinates: [75.8266, 26.9239] },
      property_pdf: "https://example.com/jaipur-heritage.pdf",
      bh: "BH-JAI-001",
      isOnline: true,
      BhJsonData: { bhCode: "BH013", manager: "Geeta Rathore" },
      lastNotificationSent: new Date(),
      otp: 112244,
      otp_expires: new Date(Date.now() + 10 * 60 * 1000),
      isPaid: true,
      RechargeData: { rechargePlan: "MONTHLY", expireData: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000), approveRecharge: true, onHowManyEarning: "Unlimited", whichDateRecharge: new Date() },
      Documents: [{ d_type: "PAN", d_url: "https://example.com/pan4.pdf", d_public_id: "pan_004" }],
    },
    {
      hotel_name: "Amber Fort View Resort",
      hotel_zone: "Amer",
      hotel_address: "Near Amber Fort, Jaipur",
      hotel_owner: "Lakshmi Choudhary",
      hotel_phone: "9999990014",
      amenities: { AC: true, freeWifi: true, kitchen: true, TV: true, powerBackup: true, geyser: true, parkingFacility: true, elevator: false, cctvCameras: true, diningArea: true, privateEntrance: true, reception: true, caretaker: true, security: true, checkIn24_7: true, dailyHousekeeping: true, fireExtinguisher: true, firstAidKit: true, buzzerDoorBell: false, attachedBathroom: true },
      contactNumberVerify: true,
      isVerifiedTag: false,
      DocumentUploaded: true,
      DocumentUploadedVerified: true,
      isBlockByAdmin: false,
      ClearAllCheckOut: false,
      hotel_main_show_image: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?ixlib=rb-4.0.3&auto=format&fit=crop&w=1350&q=80",
      area: "Amer",
      hotel_geo_location: { type: "Point", coordinates: [75.8513, 26.9855] },
      property_pdf: "https://example.com/amber-property.pdf",
      bh: "BH-JAI-002",
      isOnline: true,
      BhJsonData: { bhCode: "BH014", manager: "Vikram Singh" },
      lastNotificationSent: new Date(),
      otp: 556677,
      otp_expires: new Date(Date.now() + 10 * 60 * 1000),
      isPaid: false,
      RechargeData: { rechargePlan: "TRIAL", expireData: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000), approveRecharge: true, onHowManyEarning: "Limited", whichDateRecharge: new Date() },
      Documents: [],
    },
  ];

  try {
    await HotelUser.deleteMany({}); // Optional: clear existing data before seeding
    await HotelUser.insertMany(hotels);
    console.log("✅ Hotel seed completed: 12 hotels added (6 Delhi, 4 Noida, 2 Gurgaon, 2 Jaipur)");
  } catch (error) {
    console.error("❌ Hotel seed failed:", error.message);
  }
};

module.exports = seedHotels;